version: "2"
run:
  issues-exit-code: 1

linters:
  default: none
  enable:
    - bodyclose
    - dogsled
    - errcheck
    - errorlint
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - whitespace
  settings:
    goconst:
      min-len: 3
      min-occurrences: 5
    gocritic:
      enabled-tags:
        - diagnostic
        - performance
        - style
    gocyclo:
      min-complexity: 21
    govet:
      enable:
        - shadow
    nolintlint:
      require-explanation: true
      require-specific: true
    misspell:
      locale: US
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - govet
        text: 'shadow: declaration of "(err|ctx)" shadows declaration at'
      - linters:
          - dupl
          - goconst
          - govet
          - prealloc
        path: (.+)test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
